### ISSUE TITLE
每次添加任务、更新任务都会更新配置文件，造成所有任务重新加载？

### ISSUE THREAD

**Issue by GuoMonth** [jackletter/JackTime2Run#1]
我在代码中看见，每次添加、更新job后，都会更新配置文件，并从而触发
JackTime2Run.Time2RunSrv.watch_Changed(object sender, FileSystemEventArgs e) 方法，
在此方法中有调用了LoadJob(e.FullPath)方法，并进而调用了JobHelper.Sche();方法。
`internal static void Sche()
        {
            sche.Clear();
            Jobs.ForEach(i =>
            {
                if (i.Enable == "1")
                {
                    JobDataMap map = new JobDataMap();
                    map.Add("jobname", i);
                    IJobDetail job = JobBuilder.Create<FullJob>()
                        .UsingJobData(map)
                        .WithIdentity(i.Name, i.Name)
                        .Build();

                    ICronTrigger tri = (ICronTrigger)TriggerBuilder.Create()
                        .StartNow()
                        .WithIdentity("tri_" + i.Name, "tri_" + i.Name)
                        .WithCronSchedule(i.Cron)
                        .Build();
                    sche.ScheduleJob(job, tri);
                }
            });
        }`
此方法更新了整个任务，确定是这样吗？还是我理解错了。

**Comment by jackletter** [comment]
是这样的 对定时任务的影响应该是很小的
