### ISSUE TITLE
代码编译报错

### ISSUE THREAD

**Issue by rockyc-xj** [jackletter/JackTime2Run#2]
public bool EnableJob(string name)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(name))
                {
                    Time2RunSrv.WriteLog("管理端:【Manager】启用任务[" + name + "]失败:" + "未发现有效的任务名称！");
                    return false;
                }
                lock (typeof(Time2RunSrv))
                {
                    Configuration conf = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None);
                    ConfigurationSection sec = conf.GetSection("JackTime2RunJobs");
                    string str = sec.SectionInformation.GetRawXml();
                    XmlDocument doc = new XmlDocument();
                    doc.LoadXml(str);
                    List<XmlElement> jobs = doc.ChildNodes.OfType<XmlElement>().FirstOrDefault<XmlElement>().ChildNodes.OfType<XmlElement>().Where<XmlElement>((i) => i.Name == "job").ToList<XmlElement>();
                    for (int i = 0; i < jobs.Count; i++)
                    {
                        if (jobs[i].Attributes["name"].Value == name)
                        {
                            jobs[i].SetAttribute("enable", "1");
                            break;
                        }
                    }
                    sec.SectionInformation.SetRawXml(doc.InnerXml);
                    conf.Save(ConfigurationSaveMode.Modified);
                    //此处编译报错
                    Host._srv.ReloadConf();
                    return true;
                }
            }
            catch (Exception ex)
            {
                Time2RunSrv.WriteLog("管理端:【Manager】启用任务[" + name + "]失败:" + ex.ToString());
                return false;
            }
        }

**Comment by jackletter** [comment]
什么错？

**Comment by rockyc-xj** [comment]
Host._srv.ReloadConf();  此处编译报错    _srv 字段  去调了 ReloadConf()方法？

**Comment by jackletter** [comment]
抱歉，应该是上次代码的误提交，将这一行删除就行了。

**Comment by rockyc-xj** [comment]
好的  感谢，我昨天已经改了，学习了。
